stripe_api/api/urls.py
from django.urls import path

from api.views import create_payment, get_item


app_name = 'api'

urlpatterns = [
    path('buy/<int:item_id>/', create_payment, name='payment'),
    path('item/<int:item_id>/', get_item, name='item_page'),
]

stripe_api/stripe_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
]

stripe_api/api/models.py
from django.db import models


CHOICES = (
    ("eur", "eur"),
    ("usd", "usd"),
)


class Item(models.Model):
    name = models.CharField(
        verbose_name='Name',
        max_length=200,
    )
    description = models.TextField(
        verbose_name='Description',
    )
    price = models.IntegerField(
        verbose_name='Price',
    )
    currency = models.CharField(
        verbose_name="Currency",
        max_length=10,
        choices=CHOICES,
    )

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.name

stripe_api/api/views.py
import os

from django.shortcuts import get_object_or_404, render
from rest_framework.response import Response
from rest_framework.decorators import api_view
import stripe
from dotenv import load_dotenv

from api.models import Item

load_dotenv('../infra/.env')


stripe.api_key = os.getenv('STRIPE_SK')
url_base = os.getenv('URL_PATH')


@api_view(['GET'])
def create_payment(request, item_id):
    """Функция для проведения платежа."""
    item = get_object_or_404(Item, id=item_id)
    product = stripe.Product.create(name=item.name)
    price = stripe.Price.create(
        unit_amount=item.price * 100,
        currency=item.currency,
        product=product,
    )
    items = [url_base, "item", str(item_id)]
    url = "/".join(
        [
            (u.strip("/") if index + 1 < len(items) else u.lstrip("/")) for index, u in enumerate(items)
        ]
    )
    response = stripe.checkout.Session.create(
        success_url=url,
        cancel_url=url,
        line_items=[
            {
                "price": price,
                "quantity": 1,
            },
        ],
        mode="payment",
        payment_method_types=["card",]
    )
    return Response(response["id"])


@api_view(['GET'])
def get_item(request, item_id):
    """Функция для отображения информации о товаре."""
    item = get_object_or_404(Item, id=item_id)
    context = {
        "item": item,
        "stripe_pk_key": os.getenv('STRIPE_PK')
    }
    return render(request, 'api/item_description.html', context)

stripe_api/templates/api/item_description.html
<html>
  <head>
    <title>Buy {{ item.name }}</title>
  </head>
  <body>
    <h1>{{ item.name }}</h1>
    <p>{{ item.description }}</p>
    <p>{{ item.price }} {{ item.currency }}.</p>
    <button id="buy-button">Buy</button>
    <script src="https://js.stripe.com/v3"></script>
    <script type="text/javascript">
      const stripe_pk = "{{ stripe_pk_key }}";
      var stripe = Stripe(stripe_pk);
      let url = "{% url 'api:payment' item.pk %}";
      const buyButton = document.getElementById("buy-button");
      buyButton.addEventListener('click', function(){
        fetch(url,  {method: 'GET'})
        .then(function(response) {
            return response.json();
        })
        .then(function(session) {
            return stripe.redirectToCheckout({ sessionId: session });
        })
        .then(function(result) {
            if (result.error) {
              alert(result.error.message);
            }
          });
      });
    </script>
  </body>
</html>